deployment:
  tasks:
    - export DEPLOYPATH=/home/qpxdy/snorfctionary.com/public_html/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f index.js $DEPLOYPATH
    - /bin/cp -f index.css $DEPLOYPATH
    
    - /bin/cp -R -f docs $DEPLOYPATH
    - /bin/cp -R -f media $DEPLOYPATH
    - if [ -d assets ]; then /bin/cp -R -f assets $DEPLOYPATH; fi
    
